Forum/Controllers/MessageController.cs
using Forum.Core.Interfaces.Managers;
using Forum.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Forum.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
        private readonly IMessageManager _messageManager;
        private readonly ITopicManager _topicManager;
        private readonly IUserManager _userManager;


        public MessageController()
        {

        }

        public MessageController(IMessageManager messageManager, IUserManager userManager, ITopicManager topicManager)
        {
            _messageManager = messageManager;
            _topicManager = topicManager;
            _userManager = userManager;
        }
        [AllowAnonymous]
        public ActionResult List(int topicId)
        {
            ViewBag.AuthUser = User.Identity.IsAuthenticated ? this.GetUserId() : 0;
            var messages = _messageManager.GetAllMessages().Where(x => x.TopicId == topicId).OrderBy(x => x.MessageDateTime).ToArray();
            return PartialView("MessageList", messages);
        }

        public ActionResult AddNewMessage(int topicId)
        {
            var userId = _userManager.GetAllUsers().FirstOrDefault(x => x.UserLogin == User.Identity.Name).UserId;

            var model = new MessageModel
            {
                TopicId = topicId,
                UserId = userId
            };

            return PartialView("MessageDetails", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddNewMessage(MessageModel message)
        {
            if (ModelState.IsValid)
            {
                _messageManager.AddMessage(message.MessageText, message.MessageDateTime, message.TopicId, message.UserId);
                return RedirectToAction("Topic", "Topic", new { Id = message.TopicId });
            }
            return View("MessageDetails", message);
        }

        public PartialViewResult EditMessage(int messageId)
        {
            var model = GetModel(messageId);
            return PartialView("MessageDetails", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult EditMessage(MessageModel message)
        {
            if (ModelState.IsValid)
            {
                _messageManager.EditMessage(message.MessageId, message.MessageText, message.MessageDateTime, message.TopicId, message.UserId);
                return RedirectToAction("Topic", "Topic", new { Id = message.TopicId });
            }

            return PartialView("MessageDetails", message);
        }

        private MessageModel GetModel(int messageId)
        {
            var message = _messageManager.GetMessageById(messageId);
            var model = new MessageModel
            {
                MessageId = message.MessageId,
                MessageText = message.MessageText,
                MessageDateTime = message.MessageDateTime,
                TopicId = message.TopicId,
                UserId = message.UserId
            };

            return model;
        }


        public ActionResult DeleteMessage(int messageId)
        {
            try
            {

                var model = GetModel(messageId);
                return View(model);
            }

            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult DeleteMessage(MessageModel message)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int Id = message.TopicId;
                    _messageManager.DeleteMessage(message.MessageId);
                    return RedirectToAction("Topic", "Topic", new { Id });
                }
                else
                {
                    return HttpNotFound();
                }

            }

            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }
        [NonActionAttribute]
        private int GetUserId()
        {

            int result = _userManager.GetAllUsers().FirstOrDefault(x => x.UserLogin == User.Identity.Name).UserId;
            return result;
        }
    }
}

Forum/Controllers/TopicController.cs
using Forum.Core.Interfaces.Managers;
using Forum.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Forum.Controllers
{
    [Authorize]
    public class TopicController : Controller
    {
        private readonly ITopicManager _topicManager;
        private readonly IUserManager _userManager;

        public TopicController()
        {

        }

        public TopicController(ITopicManager topicManager, IUserManager userManager)
        {
            _topicManager = topicManager;
            _userManager = userManager;
        }
        
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index(int? userId)
        {
            ViewData["userId"] = userId == null ? 0 : this.GetUserId();
            var topics = _topicManager.GetAllTopics().OrderBy(x => x.TopicDateTime).ToArray();
            return View("TopicList", topics);
        }
        [AllowAnonymous]
        public ActionResult Topic(int id)
        {

            ViewBag.AuthUser =User.Identity.IsAuthenticated ? this.GetUserId() : 0;
            var model = GetModel(id);
            return View("Topic", model);
        }
        public ActionResult AddNewTopic(int userId)
        {
            var model = new TopicModel { UserId = userId != 0 ? userId : this.GetUserId() };
            return View("TopicDetails", model);

        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddNewTopic(TopicModel topic)
        {
            if (!string.IsNullOrEmpty(topic.TopicName))
            {
                var record = _topicManager.GetAllTopics()
                    .FirstOrDefault(x => string.Equals(x.TopicName, topic.TopicName, StringComparison.InvariantCultureIgnoreCase));
                if (record != null) ModelState.AddModelError(nameof(topic.TopicName), $"We already have Topic '{topic.TopicName}' in DB");
            }

            if (ModelState.IsValid)
            {
                _topicManager.AddTopic(topic.TopicName, topic.TopicText, topic.TopicDateTime, topic.UserId);
                return RedirectToAction("Index", topic.UserId);
            }
            return View("TopicDetails", topic);
        }

        public ActionResult EditTopic(int topicId)
        {
            var model = GetModel(topicId);
            return PartialView("TopicDetails", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult EditTopic(TopicModel topic)
        {
            if (!string.IsNullOrEmpty(topic.TopicName))
            {
                var oldTopic = _topicManager.GetTopicById(topic.TopicId);
                if (!oldTopic.TopicName.Equals(topic.TopicName, StringComparison.InvariantCultureIgnoreCase))
                {
                    var record = _topicManager.GetAllTopics()
                        .FirstOrDefault(x => string.Equals(x.TopicName, topic.TopicName, StringComparison.InvariantCultureIgnoreCase));

                    if (record != null) ModelState.AddModelError(nameof(topic.TopicName), $"We already have topic '{topic.TopicName}' in DB");
                }
            }
            if (ModelState.IsValid)
            {
                _topicManager.EditTopic(topic.TopicId, topic.TopicName, topic.TopicText, topic.TopicDateTime, topic.UserId);
                return RedirectToAction("Topic", new { id = topic.TopicId });
            }

            return PartialView("TopicDetails", topic);
        }

        private TopicModel GetModel(int topicId)
        {
            var topic = _topicManager.GetTopicById(topicId);
            var model = new TopicModel
            {
                TopicId = topic.TopicId,
                TopicName = topic.TopicName,
                TopicText = topic.TopicText,
                TopicDateTime = topic.TopicDateTime,
                UserId = topic.UserId
            };

            return model;
        }


        public ActionResult DeleteTopic(int topicId)
        {
            try
            {

                var model = GetModel(topicId);
                return View(model);
            }

            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult DeleteTopic(TopicModel topic)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _topicManager.DeleteTopic(topic.TopicId);
                    return RedirectToAction("Index");
                }
                else
                {
                    return HttpNotFound();
                }

            }

            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }
        [NonActionAttribute]
        private int GetUserId()
        {

            int result = _userManager.GetAllUsers().FirstOrDefault(x => x.UserLogin == User.Identity.Name).UserId;
            return result;
        }
    }
}

Forum/Views/Topic/DeleteTopic.cshtml
@model Forum.Models.TopicModel

@{
    ViewBag.Title = "Topic Delete";
}


<h3>Are you sure you want to delete this topic?</h3>

<div class="container body-content" style="margin-top: 20px;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.HiddenFor(x => x.TopicText)
                @Html.HiddenFor(x => x.TopicDateTime)
                @Html.HiddenFor(x => x.TopicName)
                @Html.DisplayNameFor(model => model.TopicName) :

                <strong>@Html.DisplayFor(model => model.TopicName)</strong>
                @Html.ValidationMessageFor(model => model.TopicName, "", new { @class = "text-danger" })

                <div class="row" style="display: flex; justify-content: center;">
                    <input type="submit" value="Delete" class="btn btn-danger" style="margin-right: 20px;" />
                    @Html.ActionLink("Back to List", "Topic", "Topic", new { Id = Model.TopicId }, htmlAttributes: new { id = "AddLink", @class = "btn bg-orange btn-flat margin" })
                </div>
            </div>
        </div>
    }

</div>

Forum/Views/Topic/Topic.cshtml
@model  Forum.Models.TopicModel

@{var AuthUser = ViewBag.AuthUser; }
<div class="row" style="margin: 20px 0px; outline: 3px solid white;" id="topic-@Model.TopicId">
    <div class="col-xs-2" style="display: flex;align-items: center;justify-content: center;">
        @Html.Action("UserDetails", "Account", new { UserId = Model.UserId })
    </div>
    <div class="col-xs-10">
        <h3>
            <strong>@Model.TopicName</strong>
        </h3>
        <p style="margin: 0; text-align: justify;">@Html.Raw(@Model.TopicText)</p>
        @if (AuthUser > 0 && AuthUser == Model.UserId)
        {
            <div class="row" style="display: flex; justify-content: center;">
                <div id="openTopicModalEdit">
                </div>
                <div class="row" style="display: flex; justify-content: center;">
                    @Ajax.ActionLink("Edit", "EditTopic", new { TopicId = Model.TopicId}, new AjaxOptions {
                        UpdateTargetId = "openTopicModalEdit", InsertionMode = InsertionMode.Replace,
                        OnSuccess = "afterTopicLoad("+ Model.TopicId + ")" },
                        new {@class = "btn btn-success btn-sm", style = "margin-right: 25px;" })
                    @Html.ActionLink("Delete", "DeleteTopic", new { TopicId = Model.TopicId }, new { @class = "btn btn-primary btn-danger btn-sm" })
                </div>
            </div>
        }
        <div style="display: flex; margin: 10px;">
            @if (AuthUser > 0)
            {
                <div id="openNewMessageModal">
                </div>
                <div style="width: 50%; text-align: right;">
                    @Ajax.ActionLink("New Message", "AddNewMessage", "Message", new { topicId = Model.TopicId }, new AjaxOptions
                    {
                        UpdateTargetId = "openNewMessageModal",
                        InsertionMode = InsertionMode.Replace,
                        OnSuccess = "afterNewMessageLoad()"
                    }, new { @class = "btn btn-info btn-sm", style = ""})
                </div>
            }
                <div style="width: 50%; text-align: right;">
                    @Model.TopicDateTime
                </div>
        </div>
        
    </div>

</div>

<div class="row" id="messageList" style="margin: 0px;">
    <div class="col-xs-12">
        @Html.Action("List", "Message", new { TopicId = Model.TopicId })
    </div>
</div>
@section scripts {
    <script>

        function afterMsgLoad(messageId) {
            var mId = messageId;
            $("#messageModalEdit-" + messageId).dialog({
                autoOpen: false,
                width: 800,
                height: 480,
                minWidth: 400,
                minHeight: 200,
                close: function () {
                    console.log(mId);
                    $('#MessageText-' + mId).summernote('destroy');
                }
            });
            $("#messageModalEdit-" + messageId).dialog('open');

            $('#MessageText-' + messageId).summernote({
                tabsize: 1,
                focus: true,
                width: 750,
                height: 200
            });
            $("#MessageText-" + messageId).summernote("code", $('#MessageText-' + messageId).val());

            $("#saveMessage-" + messageId).click(function() {
                $("#MessageText-" + messageId).val($('#MessageText-' + messageId).summernote("code"));
                console.log($('#MessageText-' + messageId).summernote("code"));
                $("#messageModalEdit-" + messageId).hide();
                $("#MessageText-" + messageId).summernote("destroy");
                $("#messageForm-" + messageId).submit();
            });
        }

        function afterTopicLoad(topicId) {
            var tId = topicId;
            $("#topicModalEdit-" + topicId).dialog({
                autoOpen: false,
                width: 800,
                height: 480,
                minWidth: 400,
                minHeight: 200,
                close: function () {
                    console.log(tId);
                    $('#TopicText-' + tId).summernote('destroy');
                }
            });
            $("#topicModalEdit-" + topicId).dialog('open');

            $('#TopicText-' + topicId).summernote({
                tabsize: 1,
                focus: true,
                width: 750,
                height: 200
            });
            $("#TopicText-" + topicId).summernote("code", $('#TopicText-' + topicId).val());

            $("#saveTopic-" + topicId).click(function () {
                $("#TopicText-" + topicId).val($('#TopicText-' + topicId).summernote("code"));
                console.log($('#MessageText-' + topicId).summernote("code"));
                $("#TopicText-" + topicId).summernote("destroy");
                $("#topicForm-" + topicId).submit();
            });
        }

        function afterNewMessageLoad() {
            $("#openNewMessageModal").dialog({
                autoOpen: false,
                width: 800,
                height: 480,
                minWidth: 400,
                minHeight: 200,
                close: function () {
                    $('#MessageText').summernote('destroy');
                }
            });
            $("#openNewMessageModal").dialog('open');

            $('#MessageText').summernote({
                tabsize: 1,
                focus: true,
                width: 750,
                height: 200
            });
            
            $("#saveMessage-0").click(function () {
                $("#MessageText").val($('#MessageText').summernote("code"));
                var msg = $('#MessageText').summernote("code");
                if (msg == "<p><br></p>") {
                    alert('Message text can\'t be empty');
            } else {
                $("#openNewMessageModal").hide();
                $("#MessageText").summernote("destroy");
                $("#messageForm").submit();
            }
        });
    }

   	
            var header = $('header');
      
            window.onscroll = function(){

                if (window.pageYOffset > 80) {
                    header.css("opacity","0.8");
                }
                else{
                    header.css("opacity", "1");
                }
            }


    </script>
}

Forum/Views/Topic/TopicDetails.cshtml
@model  Forum.Models.TopicModel

@{
    var action = Model.TopicId > 0 ? "EditTopic" : "AddNewTopic";
    var header = Model.TopicId > 0 ? "Edit topic" : "Add new topic";
    var buttonText = Model.TopicId > 0 ? "Save" : "Create";
    var topicModal = Model.TopicId > 0 ? "topicModalEdit-" + Model.TopicId : "topicModalNew";
}

<div id="@topicModal">
    @using (Html.BeginForm(action, "Topic", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "topicForm" + (Model.TopicId > 0 ? "-" + Model.TopicId : "") }))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="text-align: center">@header</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.TopicId)
        @Html.HiddenFor(model => model.UserId, new { Value = Model.UserId })

        <div class="form-group">
            <div class="col-md-12" style="display: flex; justify-content: center;">
                <b> @Html.DisplayNameFor(model => model.TopicName) : </b>
                @Html.EditorFor(model => model.TopicName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TopicName, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.TopicId > 0)
        {
            <div class="form-group">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.TopicText, new { htmlAttributes = new { @class = "form-control", id = "TopicText" + (Model.TopicId > 0 ? "-" + Model.TopicId : "") } })
                    @Html.ValidationMessageFor(model => model.TopicText, "", new { @class = "text-danger" })
                </div>

            </div>
        }
        else
        {
            <div class="form-group">
                <div class="col-md-12" style="display: flex; justify-content: center;">
                    @Html.EditorFor(model => model.TopicText, new { htmlAttributes = new { @class = "form-control", id = "TopicText" + (Model.TopicId > 0 ? "-" + Model.TopicId : "") } })
                    @Html.ValidationMessageFor(model => model.TopicText, "", new { @class = "text-danger" })
                </div>

            </div>
        }
        <div class="form-group">
            <div class="col-md-12">
                @Html.HiddenFor(model => model.TopicDateTime, new { htmlAttributes = new { @class = "form-control", type = "datetime-local",
               @Value = action == "EditTopic" ? Model.TopicDateTime : Model.TopicDateTime = DateTime.Now} })
                @Html.ValidationMessageFor(model => model.TopicDateTime, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group" style="display: flex; justify-content: center;">
            <button class="btn btn-primary" id="saveTopic-@Model.TopicId" style="margin-right: 20px;">@buttonText</button>
        </div>
    </div>
    }
</div>

@section scripts {
    <script>
        $('#TopicText').summernote({
            tabsize: 1,
            focus: true,
            width: 750,
            height: 200
        });
        $("#TopicText").summernote("code", $('#TopicText').val());

        $("#saveTopic-0").click(function () {
            $("#TopicText").val($('#TopicText').summernote("code"));
            $("#TopicText").summernote("destroy");
            $("#topicForm").submit();
        });
    </script>
}

Forum/Views/Topic/TopicList.cshtml
@model Forum.Core.Models.Topic[]
@{int userId = (int)(ViewData["userId"] ?? 0); }
<div class="col-md-12">
    @foreach (var itm in Model)
    {
        @Html.Partial("TopicSummary", itm)
    }
</div>

@*<div id="openNewTopicModal">
    </div>
    <div class="btn-group pull-right" style="display: flex; justify-content: center; margin: 15px 0;">
        @Ajax.ActionLink("New Topic", "AddNewTopic", "Topic", new { UserId = userId }, new AjaxOptions
    {
       UpdateTargetId = "openNewTopicModal",
       InsertionMode = InsertionMode.Replace,
       OnSuccess = "afterNewTopicLoad()"
    }, new { @class = "btn btn-success btn-sm", style = ""})
    </div>

    @section scripts {
        <script>

            function afterNewTopicLoad() {
                $("#openNewTopicModal").dialog({
                    autoOpen: false,
                    width: 800,
                    height: 540,
                    minWidth: 400,
                    minHeight: 200,
                    close: function () {
                        $('#TopicText').summernote('destroy');
                    }
                });
                $("#openNewTopicModal").dialog('open');

                $('#TopicText').summernote({
                    tabsize: 1,
                    focus: true,
                    width: 750,
                    height: 200
                });
                $("#TopicText").summernote("code", $('#TopicText').val());

                $("#saveTopic-0").click(function () {
                    $("#TopicText").val($('#TopicText').summernote("code"));
                    $("#openNewTopicModal").hide();
                    $("#TopicText").summernote("destroy");
                    $("#topicForm").submit();
                });
            }

        </script>
    }*@

Forum/Views/Topic/TopicSummary.cshtml
@model Forum.Core.Models.Topic
<div class="well">
    <h5>@Html.ActionLink(Model.TopicName, "Topic", new { id = Model.TopicId })</h5>
        @*<a href="~/Topic/Topic?id=@Model.TopicId" style="width: 100%">*@
    <div style="height: 40px; overflow: hidden; white-space: nowrap;text-overflow: ellipsis;">@Model.TopicText</div>
</div>